-- ===========================================================================
-- FechaObra — 0002_seed_textos.sql
-- Seed da tabela global textos_padrao, nicho 'obra_reforma'.
-- 12 tipos de serviço x 4 textos (escopo, exclusoes, garantia, condicoes).
--
-- Rode DEPOIS do 0001_schema.sql. Pode reexecutar: o on conflict atualiza o
-- conteúdo em vez de duplicar.
--
-- Estes textos são ponto de partida editável pelo prestador, não contrato
-- pronto. Prazos de garantia seguem prática de mercado; o mínimo legal de
-- 90 dias para serviços (CDC art. 26) e o prazo de 5 anos do Código Civil
-- para solidez e segurança da edificação continuam valendo por cima.
-- ===========================================================================

insert into public.textos_padrao (nicho, tipo_servico, tipo_texto, conteudo) values

-- =========================== 1. PINTURA ====================================
('obra_reforma', 'pintura', 'escopo',
'Execução completa dos serviços de pintura nos ambientes descritos neste orçamento. Inclui a proteção de pisos, móveis, bancadas, esquadrias e tomadas com lona plástica e fita crepe antes do início dos trabalhos. Preparação das superfícies com raspagem e remoção de partes soltas, descascadas ou com bolhas, correção de trincas e pequenos buracos com massa corrida em áreas internas e massa acrílica em áreas externas ou úmidas, lixamento e remoção do pó. Aplicação de fundo selador ou fundo preparador de paredes conforme a condição encontrada em cada superfície. Aplicação de duas demãos de tinta na cor e no acabamento definidos com o cliente, respeitando o intervalo de secagem indicado pelo fabricante entre as demãos. Recorte de cantos, rodapés, batentes e forro feito à mão para garantir linha reta e acabamento limpo. Ao final, retirada de todas as proteções, limpeza dos respingos e entrega do ambiente varrido e pronto para uso.'),

('obra_reforma', 'pintura', 'exclusoes',
'Não estão inclusos neste orçamento: o fornecimento das tintas e massas, salvo quando houver item de material descrito na lista acima; a pintura de tetos, forros, portas, janelas, portões, grades ou armários, salvo quando descritos como itens; a remoção de papel de parede, textura, grafiato ou revestimento existente; a recuperação de paredes com infiltração ativa, mofo recorrente ou reboco solto em grande extensão, que exigem tratamento prévio e serão orçados à parte; o reboco novo, o emassamento de parede nunca pintada e a regularização de superfícies fora de esquadro; a pintura de fachadas com necessidade de andaime tubular, balancim ou trabalho em altura com acesso por corda; a movimentação de móveis pesados, eletrodomésticos e objetos frágeis, que devem ser retirados do ambiente pelo cliente antes do início; serviços elétricos, troca de tomadas e interruptores; e a retirada de entulho fora do volume gerado pela própria pintura.'),

('obra_reforma', 'pintura', 'garantia',
'Garantia de 12 meses sobre a mão de obra, contados da data de conclusão do serviço, cobrindo descascamento, bolhas, falhas de aderência, manchas de emenda entre demãos e defeitos de acabamento decorrentes da execução. A garantia não cobre danos causados por infiltração, umidade ascendente, vazamento, mau uso, limpeza com produtos abrasivos, riscos, batidas, movimentação de móveis, nem o desbotamento natural da cor pela exposição ao sol e ao tempo, que varia conforme a qualidade da tinta escolhida. Tintas e materiais fornecidos pelo cliente seguem a garantia do próprio fabricante. Constatado o defeito dentro do prazo, o reparo é feito sem custo de mão de obra, mediante agendamento.'),

('obra_reforma', 'pintura', 'condicoes',
'Entrada de 40% na assinatura do orçamento, para compra de material e reserva da data na agenda. Os 60% restantes na entrega do serviço, após vistoria conjunta do ambiente. Em serviços com prazo acima de 15 dias, o saldo pode ser dividido em parcelas semanais conforme o avanço da obra, combinadas por escrito antes do início. Aceitamos Pix, dinheiro, transferência bancária e cartão de crédito em até 6 vezes, sendo que no cartão incide a taxa da operadora sobre o valor parcelado. O início dos trabalhos fica condicionado à confirmação do pagamento da entrada. Este orçamento tem validade conforme a data indicada e os preços podem ser revistos após esse prazo em razão da variação do custo dos materiais.'),

-- =========================== 2. ELÉTRICA ===================================
('obra_reforma', 'eletrica', 'escopo',
'Execução dos serviços elétricos descritos neste orçamento, seguindo a norma NBR 5410. Inclui o desligamento seguro do circuito antes de qualquer intervenção, a abertura de rasgos em alvenaria para passagem de eletrodutos quando necessário, o assentamento de caixas de passagem e caixas 4x2 e 4x4 no nível e no prumo, a passagem de cabeamento com bitola dimensionada para a carga de cada circuito e o fechamento dos rasgos com argamassa. Instalação de tomadas, interruptores, pontos de luz, luminárias e demais dispositivos previstos nos itens acima. Montagem e organização do quadro de distribuição com identificação de cada disjuntor por circuito, separação entre circuitos de iluminação, tomadas de uso geral e tomadas de uso específico, e instalação de dispositivo DR quando previsto. Ao final, teste ponto a ponto de todos os dispositivos instalados, verificação de aterramento, medição de tensão e entrega do quadro identificado, com demonstração do funcionamento ao cliente.'),

('obra_reforma', 'eletrica', 'exclusoes',
'Não estão inclusos neste orçamento: o fornecimento de fios, cabos, disjuntores, quadros, tomadas, interruptores e luminárias, salvo quando descritos como itens de material acima; o projeto elétrico assinado por engenheiro e a ART ou RRT correspondente; a troca do padrão de entrada de energia, o aumento de carga junto à concessionária e qualquer serviço no ramal de entrada, que são de responsabilidade da concessionária e exigem processo próprio; a substituição de toda a fiação do imóvel quando o orçamento previr apenas pontos específicos; o acabamento de pintura, massa ou revestimento sobre os rasgos fechados, entregues apenas com a argamassa nivelada; instalação de sistemas de automação, cerca elétrica, interfone, antena, rede de dados e câmeras, salvo se descritos; o conserto de aparelhos e eletrodomésticos; e a correção de instalações antigas fora do escopo contratado, que serão avaliadas e orçadas separadamente caso sejam encontradas durante a execução.'),

('obra_reforma', 'eletrica', 'garantia',
'Garantia de 12 meses sobre a mão de obra, contados da conclusão do serviço, cobrindo falhas de execução como mau contato, emenda mal feita, aquecimento de conexão, inversão de fase e neutro, dimensionamento incorreto de condutor e defeito na montagem do quadro. Materiais e dispositivos fornecidos por nós seguem a garantia do fabricante, normalmente de 12 meses, intermediada por nós junto ao fornecedor. A garantia não cobre queima de equipamentos por oscilação, surto ou descarga atmosférica da rede da concessionária, sobrecarga causada pela ligação de aparelhos acima da capacidade do circuito, intervenção de terceiros na instalação após a entrega, nem defeitos em materiais fornecidos pelo cliente. Qualquer alteração feita por outro profissional nos pontos executados encerra a garantia sobre o trecho alterado.'),

('obra_reforma', 'eletrica', 'condicoes',
'Entrada de 50% na aprovação do orçamento, destinada à compra de material elétrico e à reserva da data. Saldo de 50% na conclusão, após os testes finais e a entrega do quadro identificado. Em obras com prazo superior a 20 dias, o pagamento pode ser dividido por etapas concluídas, com medição combinada por escrito antes do início. Aceitamos Pix, dinheiro, transferência bancária e cartão de crédito em até 6 vezes, com a taxa da operadora acrescida no parcelamento. Serviços de emergência fora do horário comercial, aos domingos e feriados têm acréscimo, informado e aprovado antes do atendimento. Materiais comprados pelo cliente devem estar no local no dia agendado para o início, sob pena de remarcação.'),

-- ========================== 3. HIDRÁULICA ==================================
('obra_reforma', 'hidraulica', 'escopo',
'Execução dos serviços hidráulicos descritos neste orçamento, em água fria, água quente e esgoto conforme o caso. Inclui o fechamento do registro geral e o esvaziamento da tubulação antes da intervenção, a abertura de rasgos em alvenaria ou piso para acesso e passagem de tubulação quando necessário, o corte, a soldagem e o assentamento de tubos e conexões em PVC, CPVC ou PPR conforme a aplicação, com caimento correto nas linhas de esgoto para evitar retorno e entupimento. Instalação de registros, misturadores, torneiras, sifões, válvulas, caixas sifonadas e louças previstas nos itens acima. Teste de estanqueidade das linhas de água sob pressão antes do fechamento dos rasgos, para garantir que não há vazamento em nenhuma conexão nova. Fechamento dos rasgos com argamassa e limpeza do local. Ao final, religamento do sistema, verificação de vazão e pressão em cada ponto e demonstração do funcionamento ao cliente.'),

('obra_reforma', 'hidraulica', 'exclusoes',
'Não estão inclusos neste orçamento: o fornecimento de tubos, conexões, registros, metais, louças, caixas acopladas e assentos, salvo quando descritos como itens de material acima; o acabamento de pintura, revestimento, azulejo ou porcelanato sobre os rasgos fechados, entregues apenas com argamassa nivelada; a troca completa da tubulação do imóvel quando o orçamento previr apenas trechos ou pontos específicos; a limpeza e o desentupimento de rede de esgoto, caixa de gordura e fossa com equipamento de hidrojateamento; a impermeabilização de box, sacada e laje; a instalação de aquecedor a gás, boiler e toda a rede de gás, que exige profissional habilitado específico; a localização de vazamento com equipamento de geofone ou câmera, orçada à parte; a recuperação de estrutura danificada por vazamento antigo; e o reparo de problemas na rede pública ou no ramal da concessionária.'),

('obra_reforma', 'hidraulica', 'garantia',
'Garantia de 12 meses sobre a mão de obra, contados da conclusão do serviço, cobrindo vazamento em conexão executada, falha de solda, caimento incorreto de esgoto e defeito na instalação de metais e louças. Materiais fornecidos por nós seguem a garantia do fabricante. A garantia não cobre entupimento por mau uso, como descarte de gordura, fio dental, cabelo, papel e objetos na rede, nem vazamento em trecho antigo da tubulação que não fez parte do serviço contratado, nem danos causados por golpe de aríete decorrente de pressão irregular da rede, obras de terceiros ou movimentação estrutural do imóvel. Louças e metais fornecidos pelo cliente têm garantia apenas quanto à instalação, não quanto ao produto.'),

('obra_reforma', 'hidraulica', 'condicoes',
'Entrada de 50% na aprovação do orçamento, para compra de material e reserva da data. Saldo de 50% na conclusão, após o teste de estanqueidade e a vistoria conjunta. Em serviços de reforma completa de banheiro ou troca de prumada, o pagamento pode ser dividido em etapas conforme o avanço, definidas por escrito antes do início. Aceitamos Pix, dinheiro, transferência bancária e cartão de crédito em até 6 vezes, com a taxa da operadora acrescida no parcelamento. Atendimentos de emergência com vazamento ativo, fora do horário comercial, aos domingos e feriados, têm valor diferenciado, informado e aprovado antes do deslocamento. Caso a abertura da parede ou do piso revele problema diferente do diagnosticado, o serviço é interrompido e um orçamento complementar é apresentado antes de qualquer continuidade.'),

-- ======================= 4. DRYWALL / GESSO ================================
('obra_reforma', 'drywall_gesso', 'escopo',
'Execução dos serviços em drywall e gesso descritos neste orçamento. Inclui a marcação do projeto no piso e no teto conforme o layout aprovado, a fixação de guias e montantes em perfis de aço galvanizado no espaçamento correto para a altura e a carga previstas, o reforço interno nos pontos de fixação de televisão, armário, prateleira, bancada e demais cargas informadas pelo cliente, e a passagem de eletrodutos e caixas dentro da estrutura antes do fechamento. Fechamento com placas de drywall do tipo adequado a cada ambiente, sendo placa branca standard em áreas secas e placa verde resistente à umidade em áreas molhadas. Tratamento das juntas com fita e massa própria em três demãos, com lixamento entre elas, e acabamento nos cantos com cantoneira. Nos forros, nivelamento a laser ou mangueira de nível, estrutura em perfil suspensa por tirantes e previsão dos pontos de luz e de acesso. Entrega da superfície lisa, no prumo e pronta para receber pintura, com o ambiente varrido.'),

('obra_reforma', 'drywall_gesso', 'exclusoes',
'Não estão inclusos neste orçamento: a pintura, o selador e o emassamento final de nivelamento fino da superfície, salvo quando descritos como itens acima; o fornecimento de placas, perfis, massa, fita e parafusos, salvo quando descritos como material; a instalação elétrica, hidráulica e de ar-condicionado dentro da estrutura, apenas a previsão de passagem quando informada com antecedência; a demolição de paredes de alvenaria existentes e a remoção do entulho gerado por ela; a instalação de sancas, molduras e elementos decorativos não descritos; a fixação de objetos pelo cliente após a entrega em pontos sem reforço previsto, que não é coberta; o isolamento acústico com lã de vidro, lã de rocha ou placa acústica, salvo quando orçado como item; e a correção de desnível de piso ou de laje fora de esquadro que exija estrutura adicional, situação que será apontada e orçada antes da execução.'),

('obra_reforma', 'drywall_gesso', 'garantia',
'Garantia de 12 meses sobre a mão de obra, contados da conclusão, cobrindo trinca em junta tratada, desnivelamento de forro, soltura de placa, falha na fixação da estrutura e defeito de acabamento nos cantos. A garantia não cobre trincas decorrentes de acomodação natural da estrutura do imóvel, movimentação por obra vizinha, infiltração vinda de laje, telhado ou tubulação, contato com água em placa standard instalada em área seca, nem furos, batidas e danos por impacto. Também não cobre a queda de objetos fixados pelo cliente em pontos onde não havia reforço previsto e informado no momento da execução. Danos causados por umidade exigem a correção prévia da origem antes de qualquer reparo em garantia.'),

('obra_reforma', 'drywall_gesso', 'condicoes',
'Entrada de 40% na aprovação do orçamento, para compra de material e reserva da data na agenda. Saldo de 60% na conclusão, após vistoria conjunta com conferência de prumo, nível e acabamento das juntas. Em obras acima de 15 dias, o saldo pode ser parcelado por etapa concluída, combinado por escrito antes do início. Aceitamos Pix, dinheiro, transferência bancária e cartão de crédito em até 6 vezes, com a taxa da operadora acrescida no parcelamento. O local deve estar livre de móveis e com energia elétrica disponível no dia agendado. Alterações de layout solicitadas depois da estrutura montada geram custo adicional de retrabalho, apresentado e aprovado antes da execução.')

,

-- ========================== 5. ALVENARIA ===================================
('obra_reforma', 'alvenaria', 'escopo',
'Execução dos serviços de alvenaria descritos neste orçamento. Inclui a marcação e o esquadrejamento das paredes conforme o projeto ou o layout aprovado com o cliente, o levantamento em bloco cerâmico ou bloco de concreto assentado com argamassa, respeitando prumo, nível e amarração entre fiadas, e a fixação da alvenaria na estrutura existente com encunhamento adequado. Execução de vergas sobre vãos de portas e janelas e contravergas sob os peitoris, dimensionadas conforme o vão, para evitar as trincas típicas nos cantos das aberturas. Chapisco em toda a superfície como ponte de aderência, seguido de reboco desempenado no prumo e no nível, com espessura uniforme, deixando a parede pronta para receber massa, revestimento ou pintura. Execução dos requadros de portas e janelas e dos arremates junto ao piso e ao teto. Ao final, retirada dos restos de argamassa, varrição do ambiente e organização do entulho gerado em ponto único definido com o cliente.'),

('obra_reforma', 'alvenaria', 'exclusoes',
'Não estão inclusos neste orçamento: o fornecimento de blocos, areia, cimento, cal e argamassa, salvo quando descritos como itens de material acima; a caçamba e a retirada do entulho da obra, que são orçadas à parte conforme o volume gerado; qualquer serviço estrutural como pilar, viga, laje, sapata, fundação e reforço de estrutura, que exigem projeto e responsabilidade técnica de engenheiro; a demolição de paredes estruturais, que só pode ser feita mediante laudo e projeto; a instalação elétrica e hidráulica embutida na parede nova, salvo quando descrita como item; a massa corrida, o revestimento cerâmico e a pintura sobre o reboco entregue; a instalação de portas, janelas e batentes; o contrapiso e a regularização de piso; e a correção de desaprumo ou recalque da estrutura existente do imóvel, que será apontada antes do início e orçada separadamente.'),

('obra_reforma', 'alvenaria', 'garantia',
'Garantia de 12 meses sobre a mão de obra, contados da conclusão do serviço, cobrindo falhas de execução como reboco solto ou oco, parede fora de prumo ou fora de esquadro, ausência ou má execução de verga e contraverga e falha no encunhamento. Para serviços que envolvam solidez e segurança da edificação, prevalece o prazo legal de 5 anos previsto no Código Civil. A garantia não cobre trincas decorrentes de acomodação natural da construção nos primeiros meses, movimentação do solo, recalque de fundação existente, infiltração, obras executadas por terceiros na mesma estrutura, nem dano por impacto. Materiais fornecidos pelo cliente seguem a garantia do próprio fabricante e fogem da nossa responsabilidade quanto à qualidade do produto.'),

('obra_reforma', 'alvenaria', 'condicoes',
'Entrada de 40% na aprovação do orçamento, para compra de material e reserva da equipe na agenda. Saldo de 60% na conclusão, após vistoria conjunta com conferência de prumo, nível e esquadro. Em obras com prazo acima de 20 dias, o pagamento é dividido em medições por etapa concluída, definidas por escrito antes do início dos trabalhos. Aceitamos Pix, dinheiro, transferência bancária e cartão de crédito em até 6 vezes, com a taxa da operadora acrescida no parcelamento. O local deve ter água e energia disponíveis e ponto de descarga de material acessível. Caso o material fornecido pelo cliente não esteja no local na data agendada, a equipe é remanejada e a data é reprogramada conforme a disponibilidade da agenda.'),

-- ==================== 6. PISO E REVESTIMENTO ===============================
('obra_reforma', 'piso_revestimento', 'escopo',
'Execução do assentamento de piso e revestimento nos ambientes descritos neste orçamento. Inclui a conferência da superfície quanto a nível, caimento e resistência antes do início, a regularização de pequenas imperfeições do contrapiso, a paginação das peças combinada previamente com o cliente para definir o ponto de partida, o sentido do assentamento e a posição dos recortes, buscando o melhor aproveitamento e o menor número de peças cortadas em local visível. Assentamento com argamassa colante do tipo adequado à peça e ao ambiente, aplicada com desempenadeira dentada e com dupla colagem nas peças de grande formato, mantendo juntas de espessura uniforme com espaçadores e conferência constante de nível e alinhamento. Execução dos recortes em serra e furos para ralos, vasos e tomadas. Após a cura, rejuntamento na cor escolhida, limpeza do excesso e acabamento das juntas de canto e de dilatação com material apropriado. Instalação de rodapés e soleiras quando previstos nos itens. Entrega do ambiente limpo, com as peças conferidas quanto a som oco e desalinhamento.'),

('obra_reforma', 'piso_revestimento', 'exclusoes',
'Não estão inclusos neste orçamento: o fornecimento de porcelanato, cerâmica, argamassa colante, rejunte, rodapé e soleira, salvo quando descritos como itens de material acima; a remoção do piso ou revestimento existente e a retirada do entulho gerado, orçadas à parte; a execução de contrapiso novo, o nivelamento de piso com desnível acentuado e a correção de caimento para ralo, que exigem serviço específico; a impermeabilização de áreas molhadas, box, sacada e laje, indispensável antes do revestimento nesses locais e não incluída aqui; a instalação hidráulica de ralos e a elétrica de pontos na parede; o polimento, o lustro e o tratamento de piso de mármore, granito e cimento queimado; a instalação de piso laminado, vinílico e de madeira, que seguem processo próprio; e a quebra de peças por qualidade do material, variação de tonalidade entre lotes e calibragem irregular de fábrica, situações que devem ser conferidas pelo cliente na compra.'),

('obra_reforma', 'piso_revestimento', 'garantia',
'Garantia de 12 meses sobre a mão de obra, contados da conclusão, cobrindo peça solta, som oco por falha de assentamento, desalinhamento de junta, desnível entre peças e falha na aplicação do rejunte. A garantia não cobre trincas e quebras causadas por impacto, queda de objetos, movimentação estrutural do imóvel, recalque, infiltração vinda de outro ponto, ausência de junta de dilatação em áreas onde ela foi recusada pelo cliente, nem manchas no rejunte por limpeza com produto ácido ou abrasivo. Variação de tonalidade entre caixas, empenamento e diferença de calibre das peças são características do produto e respondem pela garantia do fabricante. Peças fornecidas pelo cliente têm garantia apenas quanto ao assentamento.'),

('obra_reforma', 'piso_revestimento', 'condicoes',
'Entrada de 40% na aprovação do orçamento, para compra de material e reserva da data. Saldo de 60% na conclusão, após a vistoria conjunta e a conferência do rejuntamento. Em áreas acima de 100 metros quadrados ou obras com prazo superior a 15 dias, o pagamento pode ser dividido por ambiente concluído, combinado por escrito antes do início. Aceitamos Pix, dinheiro, transferência bancária e cartão de crédito em até 6 vezes, com a taxa da operadora acrescida no parcelamento. Recomendamos comprar de 10 a 15 por cento a mais de material para cobrir recortes, perdas e reposição futura, sendo essa compra de responsabilidade do cliente. O ambiente deve estar livre e com o contrapiso curado e seco na data agendada.'),

-- ========================= 7. MARCENARIA ===================================
('obra_reforma', 'marcenaria', 'escopo',
'Projeto, fabricação e instalação dos móveis planejados descritos neste orçamento. Inclui a visita técnica para medição no local, a conferência de prumo, nível e esquadro das paredes e o levantamento dos pontos de elétrica, hidráulica e gás que interferem no móvel. Elaboração do projeto executivo com vistas e detalhamento interno, apresentado ao cliente para aprovação antes do corte, momento em que ficam definidos materiais, cores, puxadores, ferragens e divisões internas. Corte e usinagem das peças em MDF com acabamento e espessura conforme especificado, fitagem de bordas em todas as faces aparentes, montagem da estrutura, instalação de corrediças, dobradiças e sistemas de abertura das linhas definidas no projeto. Instalação no local com nivelamento, fixação segura na parede conforme o tipo de alvenaria encontrada, ajuste de portas e gavetas para alinhamento de frentes e folgas uniformes, e execução dos arremates e rodapés de acabamento junto a paredes e forro. Entrega com limpeza dos móveis, regulagem final e orientação de uso e conservação ao cliente.'),

('obra_reforma', 'marcenaria', 'exclusoes',
'Não estão inclusos neste orçamento: eletrodomésticos, cooktop, coifa, forno, cuba, torneira, bancada de pedra, vidro, espelho e iluminação de LED, salvo quando descritos como itens acima; a instalação e a adequação de pontos de elétrica, hidráulica, gás e exaustão para os eletrodomésticos embutidos, que devem estar prontos e nas posições do projeto antes da montagem; o recorte e a instalação de bancada de granito, mármore, quartzo ou similar; serviços de alvenaria, gesso, pintura e reparo de parede antes ou depois da instalação; a retirada, o desmonte e o descarte de móveis existentes; o transporte de móveis por escada em edifícios sem elevador de carga ou com acesso restrito, que gera custo adicional; e alterações de projeto solicitadas após a aprovação e o início do corte das chapas, que não podem ser desfeitas e serão orçadas como item novo.'),

('obra_reforma', 'marcenaria', 'garantia',
'Garantia de 3 anos sobre a estrutura do móvel e a mão de obra de instalação, contados da entrega, cobrindo defeito de fabricação, descolamento de fita de borda, falha de montagem e problema de fixação. Ferragens, corrediças, dobradiças e sistemas de abertura seguem a garantia do fabricante, que costuma ser de 1 a 10 anos conforme a linha especificada no projeto. A garantia não cobre inchaço e empenamento de MDF por contato com água, vazamento, pano molhado apoiado ou umidade excessiva no ambiente, nem riscos, batidas, desgaste natural, sobrecarga de prateleiras acima do peso recomendado, exposição direta ao sol e alterações feitas por terceiros no móvel. Diferenças naturais de tonalidade e veio entre lotes de chapa não caracterizam defeito.'),

('obra_reforma', 'marcenaria', 'condicoes',
'Entrada de 50% na aprovação do projeto executivo, que é o momento em que o material é comprado e as chapas entram em corte. Saldo de 50% no dia da instalação, após a montagem e a conferência do móvel no local. Aceitamos Pix, dinheiro, transferência bancária e cartão de crédito em até 10 vezes, com a taxa da operadora acrescida no parcelamento. O prazo de produção começa a contar da aprovação formal do projeto e da confirmação da entrada, não da data do orçamento. Alterações após a aprovação implicam novo prazo e custo adicional. O local deve estar com piso, revestimento, pintura e pontos de instalação concluídos na data agendada para a montagem, sob pena de remarcação.'),

-- ====================== 8. AR-CONDICIONADO =================================
('obra_reforma', 'ar_condicionado', 'escopo',
'Instalação completa do sistema de ar-condicionado descrito neste orçamento. Inclui a avaliação do local e a definição, junto ao cliente, do melhor posicionamento da evaporadora e da condensadora considerando a distribuição do ar, o acesso para manutenção, o caimento do dreno e a distância entre as unidades. Fixação do suporte da condensadora e da base da evaporadora nivelados e devidamente ancorados. Execução da interligação frigorígena com tubulação de cobre isolada, com curvas feitas sem amassamento, flangeamento correto e torque nas conexões. Passagem do cabo de interligação elétrica entre as unidades e do dreno com caimento contínuo para escoamento por gravidade. Vácuo na tubulação com bomba antes da liberação do gás, etapa indispensável para retirar ar e umidade do circuito e garantir a vida útil do compressor. Teste de estanqueidade, liberação da carga de gás, medição de pressão e de corrente, teste de aquecimento e resfriamento e verificação do escoamento do dreno. Acabamento com canaleta ou arremate na parede e entrega com demonstração de uso do controle e orientação de limpeza dos filtros.'),

('obra_reforma', 'ar_condicionado', 'exclusoes',
'Não estão inclusos neste orçamento: o fornecimento do aparelho, salvo quando descrito como item acima; a criação do ponto elétrico exclusivo com disjuntor dedicado no quadro, dimensionado para a carga do equipamento, que é pré-requisito e deve estar pronto antes da instalação; a perfuração de laje, viga, pilar e parede estrutural; a instalação em fachada com necessidade de andaime, balancim, plataforma elevatória ou trabalho em altura por corda, que gera custo adicional de acesso; a autorização do condomínio quanto ao posicionamento da condensadora na fachada, de responsabilidade do cliente; a tubulação de dreno para rede de esgoto com necessidade de bomba de condensado, salvo se descrita como item; o serviço de pintura, gesso e alvenaria para fechamento e acabamento do trajeto da tubulação; e a manutenção preventiva periódica, a higienização e a recarga de gás após o período de garantia.'),

('obra_reforma', 'ar_condicionado', 'garantia',
'Garantia de 12 meses sobre a mão de obra e a instalação, contados da conclusão, cobrindo vazamento de gás em conexão executada, falha no flangeamento, dreno com escoamento incorreto, fixação inadequada dos suportes e erro na interligação elétrica. O aparelho segue a garantia do fabricante, normalmente de 12 meses para o equipamento e prazo estendido para o compressor, condicionada à instalação por profissional qualificado e à manutenção periódica prevista no manual. A garantia da instalação não cobre defeito do próprio equipamento, entupimento de dreno por sujeira acumulada e falta de limpeza dos filtros, queima por oscilação da rede elétrica, ausência do disjuntor dedicado, remoção ou realocação do aparelho feita por terceiros, nem danos por descarga atmosférica. A limpeza dos filtros é responsabilidade do usuário e deve ser feita periodicamente.'),

('obra_reforma', 'ar_condicionado', 'condicoes',
'Entrada de 50% na aprovação do orçamento, para compra de tubulação, suportes e materiais de instalação e reserva da data. Saldo de 50% na conclusão, após os testes de pressão, resfriamento e escoamento do dreno. Aceitamos Pix, dinheiro, transferência bancária e cartão de crédito em até 6 vezes, com a taxa da operadora acrescida no parcelamento. Instalações com metragem de tubulação superior à prevista neste orçamento, necessidade de acesso em altura ou trajeto diferente do avaliado na visita geram custo complementar, informado e aprovado antes da execução. O ponto elétrico dedicado deve estar pronto na data agendada, sob pena de nova visita com custo de deslocamento.')
,

-- ===================== 9. IMPERMEABILIZAÇÃO ================================
('obra_reforma', 'impermeabilizacao', 'escopo',
'Execução dos serviços de impermeabilização nas áreas descritas neste orçamento. Inclui a preparação do substrato com limpeza profunda, remoção de partes soltas, óleo, poeira e resíduos, o tratamento de trincas e a execução de meia cana nos encontros entre piso e parede, ponto onde a maioria das infiltrações começa. Regularização da superfície com caimento correto na direção dos ralos, garantindo que não fique poça de água parada. Aplicação do sistema impermeabilizante especificado para cada área, seja manta asfáltica aplicada com maçarico e sobreposição nas emendas, seja argamassa polimérica ou membrana acrílica em demãos cruzadas, respeitando o consumo por metro quadrado indicado pelo fabricante e o intervalo de secagem entre as demãos. Reforço com tela ou véu de poliéster nos pontos críticos, ralos, tubulações passantes, rodapés e cantos, com subida na parede na altura recomendada. Teste de estanqueidade com lâmina de água mantida por 72 horas antes da liberação para o revestimento, com verificação do ponto inferior. Entrega com relatório do teste e orientação sobre a proteção mecânica necessária.'),

('obra_reforma', 'impermeabilizacao', 'exclusoes',
'Não estão inclusos neste orçamento: o fornecimento de manta, primer, argamassa polimérica, membrana e telas, salvo quando descritos como itens de material acima; a remoção do revestimento, do piso e do contrapiso existentes e a retirada do entulho, orçadas à parte; a execução do contrapiso de proteção mecânica sobre a impermeabilização e o assentamento do revestimento final, salvo quando descritos; o tratamento estrutural de laje com armadura exposta, corrosão ou fissura ativa, que exige avaliação de engenheiro; a substituição de ralos, tubulações e a correção de vazamentos hidráulicos, que devem ser resolvidos antes da impermeabilização; a injeção de resina para tratamento de infiltração por pressão negativa em subsolo e a impermeabilização de reservatório enterrado, que seguem sistema próprio; e a solução de infiltração cuja origem esteja fora da área contratada, como fachada, telhado, unidade vizinha ou área comum do condomínio.'),

('obra_reforma', 'impermeabilizacao', 'garantia',
'Garantia de 5 anos sobre o sistema aplicado nas áreas contratadas, contados da conclusão, cobrindo falha de estanqueidade decorrente da aplicação, descolamento de manta, falha em emenda e falha nos reforços de ralo e canto. A garantia fica condicionada à execução da proteção mecânica sobre o sistema e ao respeito ao prazo de cura antes da liberação da área. A garantia não cobre perfuração da camada impermeabilizante por serviço de terceiros, como fixação de suporte, guarda-corpo, deck, floreira e antena, nem infiltração com origem fora da área tratada, movimentação estrutural severa, recalque, entupimento de ralo por falta de manutenção, nem áreas onde o cliente tenha dispensado a subida de rodapé ou o reforço recomendado. Alterações no sistema após a entrega encerram a garantia sobre o trecho afetado.'),

('obra_reforma', 'impermeabilizacao', 'condicoes',
'Entrada de 50% na aprovação do orçamento, para compra do sistema impermeabilizante e reserva da data. Saldo de 50% após a conclusão e a aprovação do teste de estanqueidade das 72 horas. Aceitamos Pix, dinheiro, transferência bancária e cartão de crédito em até 6 vezes, com a taxa da operadora acrescida no parcelamento. O prazo informado considera condição climática favorável, já que chuva e umidade elevada impedem a aplicação e a cura do sistema, podendo estender o cronograma sem custo adicional para nenhuma das partes. A área deve estar liberada, sem tráfego e sem material estocado durante toda a execução e a cura. Caso a remoção do revestimento revele dano estrutural na laje, o serviço é interrompido e um orçamento complementar é apresentado antes da continuidade.'),

-- ========================== 10. TELHADO ====================================
('obra_reforma', 'telhado', 'escopo',
'Execução dos serviços de telhado descritos neste orçamento. Inclui a inspeção prévia da cobertura e da estrutura de apoio, com registro fotográfico dos pontos críticos encontrados, e a montagem do acesso seguro com uso de equipamento de proteção individual e linha de vida quando necessário. Conforme o escopo contratado, execução da revisão com realinhamento de telhas deslocadas, substituição das peças trincadas ou quebradas, recolocação de cumeeiras e rufos, limpeza de calhas e condutores e desobstrução do escoamento. Nos serviços de reforma da cobertura, remoção das telhas existentes, conferência e substituição de peças comprometidas do madeiramento ou da estrutura metálica, tratamento contra cupim e umidade quando previsto, ajuste do caimento e reassentamento das telhas com alinhamento, transpasse e amarração corretos. Execução dos arremates com rufos, calhas, algeroz e vedação nos encontros com paredes, chaminés e claraboias, pontos onde as goteiras mais aparecem. Teste com molhagem dirigida nos pontos tratados quando aplicável e entrega com o entulho recolhido em ponto único e as calhas limpas.'),

('obra_reforma', 'telhado', 'exclusoes',
'Não estão inclusos neste orçamento: o fornecimento de telhas, madeiramento, estrutura metálica, calhas, rufos e mantas, salvo quando descritos como itens de material acima; o projeto estrutural de cobertura e a responsabilidade técnica de engenheiro, necessários em reformas que alterem a estrutura ou o vão; a caçamba e o transporte do entulho, orçados à parte conforme o volume; a substituição integral do madeiramento quando o orçamento previr apenas peças pontuais, sendo que a real extensão do dano só se confirma após a remoção das telhas; o forro, o gesso e a pintura interna danificados por goteira anterior; a instalação de laje, platibanda e reforço estrutural; a impermeabilização de laje descoberta, que segue sistema próprio; e serviços em cobertura de área comum de condomínio sem autorização formal do síndico.'),

('obra_reforma', 'telhado', 'garantia',
'Garantia de 2 anos sobre a mão de obra nos serviços de reforma e substituição de cobertura, e de 12 meses nos serviços de revisão e reparo pontual, contados da conclusão, cobrindo goteira nos pontos efetivamente tratados, falha de alinhamento e transpasse, defeito nos rufos e arremates executados e falha na fixação das telhas. Materiais fornecidos por nós seguem a garantia do fabricante. A garantia não cobre infiltração em áreas do telhado que não fizeram parte do escopo contratado, dano por vento forte, granizo, queda de árvore e eventos climáticos extremos, deslocamento de telhas por trânsito de pessoas sobre a cobertura, entupimento de calha por folhas e sujeira acumulada, nem falha de estrutura antiga já apontada na inspeção e cuja substituição foi recusada pelo cliente. A limpeza periódica de calhas é responsabilidade do proprietário.'),

('obra_reforma', 'telhado', 'condicoes',
'Entrada de 40% na aprovação do orçamento, para compra de material e reserva da equipe. Saldo de 60% na conclusão, após a vistoria conjunta da cobertura. Em reformas completas de cobertura, o pagamento é dividido por etapas conforme o avanço, definidas por escrito antes do início. Aceitamos Pix, dinheiro, transferência bancária e cartão de crédito em até 6 vezes, com a taxa da operadora acrescida no parcelamento. O prazo considera condição climática favorável, e dias de chuva interrompem o trabalho por segurança da equipe, prorrogando o cronograma sem custo adicional. Como parte do dano na estrutura só fica visível após a retirada das telhas, peças adicionais comprometidas encontradas durante a execução são fotografadas, apresentadas ao cliente e orçadas como complemento antes de qualquer substituição.'),

-- =================== 11. ESQUADRIAS E VIDROS ===============================
('obra_reforma', 'esquadrias_vidros', 'escopo',
'Fornecimento conforme os itens descritos e instalação das esquadrias e dos vidros previstos neste orçamento. Inclui a medição final no local antes da fabricação, etapa que define as dimensões definitivas e substitui qualquer medida preliminar, com conferência de prumo, nível, esquadro e largura do vão. Remoção cuidadosa da esquadria existente quando prevista, com o mínimo de dano ao acabamento ao redor. Instalação do contramarco ou fixação direta conforme o tipo de vão, com chumbamento ou parafusamento adequado à alvenaria encontrada, alinhamento no prumo e no nível e calafetação de todo o perímetro com silicone estrutural ou espuma expansiva conforme a aplicação, garantindo a vedação contra água e vento. Instalação dos vidros com as espessuras especificadas, uso de vidro temperado ou laminado onde a norma exige, colocação de borrachas, baguetes, escovas e roldanas, regulagem de folhas de correr e de abrir para deslizamento suave e fechamento alinhado. Instalação de fechos, puxadores e travas. Entrega com teste de abertura e fechamento, limpeza dos vidros e retirada das películas de proteção.'),

('obra_reforma', 'esquadrias_vidros', 'exclusoes',
'Não estão inclusos neste orçamento: os serviços de alvenaria, gesso, massa e pintura para requadro e acabamento do vão após a instalação, salvo quando descritos como itens; a adequação de vãos fora de esquadro, com desnível ou com medida diferente da levantada na visita técnica; a retirada e o descarte das esquadrias antigas removidas, salvo quando descrito; a instalação de grades, telas de proteção, persianas, cortinas e películas, salvo quando orçadas como item; o içamento de peças por fachada com uso de guindaste, plataforma ou escada de grande porte, e o transporte por escada em edifício sem elevador de carga compatível, que geram custo adicional; a aprovação do condomínio quanto ao padrão e à cor da esquadria na fachada, de responsabilidade do cliente; e serviços elétricos para automação de portões e esquadrias motorizadas.'),

('obra_reforma', 'esquadrias_vidros', 'garantia',
'Garantia de 12 meses sobre a mão de obra de instalação, contados da conclusão, cobrindo falha de vedação e infiltração pelo perímetro instalado, desalinhamento, desregulagem de folhas e defeito na fixação. As esquadrias e os componentes fornecidos por nós seguem a garantia do fabricante, normalmente de 12 meses para acessórios e roldanas e prazo maior para o perfil e a pintura eletrostática, condicionada à limpeza e à manutenção periódica previstas no manual. A garantia não cobre quebra de vidro por impacto, esforço na abertura, batida de porta pelo vento, riscos, manchas por respingo de massa, cimento e produto químico durante obras posteriores, corrosão por maresia em regiões litorâneas quando não especificada linha própria para o ambiente, nem danos por movimentação estrutural do vão. Vidros são conferidos no ato da entrega, e quebras posteriores não são cobertas.'),

('obra_reforma', 'esquadrias_vidros', 'condicoes',
'Entrada de 50% na aprovação do orçamento e na liberação da medição final, momento em que o pedido entra em fabricação. Saldo de 50% no dia da instalação, após o teste de abertura, fechamento e vedação. Aceitamos Pix, dinheiro, transferência bancária e cartão de crédito em até 10 vezes, com a taxa da operadora acrescida no parcelamento. O prazo de fabricação começa a contar da medição final e da confirmação da entrada, não da data do orçamento. Peças sob medida não admitem devolução nem alteração após a entrada em produção. O vão deve estar concluído, sem revestimento pendente que altere a medida, e o local deve estar acessível na data agendada, sob pena de remarcação com custo de novo deslocamento.'),

-- ===================== 12. REFORMA COMPLETA ================================
('obra_reforma', 'reforma_completa', 'escopo',
'Execução da reforma completa do imóvel ou dos ambientes descritos neste orçamento, com coordenação de todas as etapas e das equipes envolvidas. Inclui o planejamento do cronograma por etapa e a definição da ordem de execução, começando pela demolição e pela remoção dos revestimentos e das instalações a serem substituídos, com proteção das áreas que permanecem. Em seguida, execução das alterações de alvenaria e drywall conforme o layout aprovado, passagem das novas instalações elétricas e hidráulicas com teste antes do fechamento, impermeabilização das áreas molhadas com teste de estanqueidade, contrapiso e regularização, assentamento de pisos e revestimentos, tratamento de superfícies, massa, selador e pintura, instalação de louças, metais, luminárias, portas e acabamentos. Acompanhamento diário da obra, controle de qualidade em cada etapa antes de liberar a seguinte e comunicação periódica do avanço ao cliente. Entrega final com vistoria conjunta ambiente por ambiente, correção dos apontamentos levantados na vistoria e limpeza grossa do imóvel, pronto para a limpeza fina e a mudança.'),

('obra_reforma', 'reforma_completa', 'exclusoes',
'Não estão inclusos neste orçamento: os materiais de acabamento de escolha do cliente, como porcelanato, louças, metais, luminárias, tintas, portas e ferragens, salvo quando descritos como itens acima com marca e referência definidas; móveis planejados, eletrodomésticos, bancadas de pedra, vidros e espelhos, salvo quando orçados; o projeto de arquitetura, o projeto estrutural, o projeto elétrico e hidráulico e as respectivas responsabilidades técnicas; a aprovação de projeto em prefeitura, a documentação exigida pelo condomínio e as taxas correspondentes; a caçamba e a retirada de entulho, orçadas conforme o volume real gerado; qualquer intervenção estrutural em pilar, viga, laje e fundação, que exige projeto de engenheiro; o tratamento de patologias ocultas como cupim, infiltração antiga, fiação deteriorada e tubulação corroída, que só aparecem após a demolição; a limpeza fina pós-obra e a mudança; e a hospedagem ou a guarda de móveis do cliente durante a obra.'),

('obra_reforma', 'reforma_completa', 'garantia',
'Garantia de 12 meses sobre a mão de obra de acabamento, contados da entrega, cobrindo falhas de execução em pintura, revestimento, gesso, instalação de louças, metais e acabamentos. Garantia de 2 anos sobre as instalações elétricas e hidráulicas executadas e de 5 anos sobre a impermeabilização das áreas molhadas. Para itens que envolvam solidez e segurança da edificação, prevalece o prazo legal de 5 anos previsto no Código Civil. Materiais fornecidos por nós seguem a garantia dos respectivos fabricantes, e materiais fornecidos pelo cliente têm cobertura apenas quanto à instalação. A garantia não cobre mau uso, desgaste natural, danos por terceiros que intervenham na obra entregue, falta de manutenção preventiva, movimentação estrutural do imóvel, infiltração vinda de área comum ou de unidade vizinha, nem alterações feitas por outro profissional, que encerram a garantia sobre o trecho alterado.'),

('obra_reforma', 'reforma_completa', 'condicoes',
'Pagamento dividido por etapas medidas, conforme cronograma acordado por escrito antes do início. Entrada de 30% na assinatura, para mobilização da equipe, compra do material inicial e reserva do período na agenda. Parcelas intermediárias liberadas ao final de cada etapa concluída e aprovada pelo cliente, tipicamente demolição e instalações, contrapiso e revestimentos, acabamento e pintura. Retenção de 10% do valor total pagos somente após a vistoria final e a correção de todos os apontamentos levantados. Aceitamos Pix, dinheiro, transferência bancária e cartão de crédito em até 12 vezes, com a taxa da operadora acrescida no parcelamento. Serviços não previstos, alterações de escopo solicitadas durante a obra e patologias ocultas encontradas após a demolição são documentados com fotos e orçados como aditivo, com aprovação por escrito do cliente antes da execução. O prazo total pode ser afetado por atraso na entrega de material de escolha do cliente e por decisões pendentes de definição.')

on conflict (nicho, tipo_servico, tipo_texto) do update
  set conteudo = excluded.conteudo;


-- ===========================================================================
-- Conferência: deve retornar 12 serviços x 4 textos = 48 linhas.
-- ===========================================================================
-- select tipo_servico, count(*) from public.textos_padrao
--  where nicho = 'obra_reforma' group by tipo_servico order by tipo_servico;
